version: '3.9'

services:
  regera-recruit:
    container_name: regera-recruit-container
    image: regera-recruit
    ports:
      - '9999:9999'
    networks:
      - backend

networks:
  backend:
    driver: bridge