spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/regera_recruit}
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: keepme2401@gmail.com
    password: tccpotdwysrognyx
  data:
    redis:
      port: 6379
      host: localhost

app:
  jwtExpirationMs: 2592000
  jwtSecret: T7EOnmBnmqvRABNZf9TsmuHLyFmauuAV66Nd8OdaTlFLBTocK2nH0NKIcwLpjJAosgGs8tV2BuuIQ2doKjiFfA==
  jwtRefresh: T9EOnmBnmqvRABNZf9TsmuHLyFmauuAV66Nd8OdaTlFLBTocK2nH0NKIcwLpjJAosgGs8tV2BuuIQ2doKjiFfA==
  jwtRefreshExpirationMs: 200000000

cloudinary:
  cloud-name: do9tp2bph
  api-key: 637613168259424
  api-secret: ryWJdtT3C2tSRVrPmxuytLiiBl0

open:
  api:
    title: Regera Recruit document
    description: API for Regera Recruit document
    version: v1.0.0
    serverUrl: http://localhost:9999
    serverName: Server Test